spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shike-m/configRep.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/