eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db?useSSL=false
  jpa:
    show-sql: true
