eureka:
  client:
    service-url:
     defaultZone: http://localhost:8671/eureka
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db?useSSL=false
    username: root
    password: root

